/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eddproyecto2;

import java.awt.event.ItemListener;
import java.io.File;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author sjgg2
 */
public class Interfaz extends javax.swing.JFrame {
    ItemListener aListener;
    HashTable Table = new HashTable(100);
    Lector lector;
    HashTable palabrasClave = new HashTable(100);

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        insertarArchivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Salida = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        consola = new javax.swing.JTextArea();
        investigacionesDisponibles = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        insertarArchivo.setText("Insertar Archivo");
        insertarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(insertarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        Salida.setColumns(20);
        Salida.setRows(5);
        jScrollPane1.setViewportView(Salida);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        consola.setColumns(20);
        consola.setRows(5);
        jScrollPane2.setViewportView(consola);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 400, 160));

        investigacionesDisponibles.setToolTipText("Investigaciones disponibles");
        investigacionesDisponibles.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                investigacionesDisponiblesItemStateChanged(evt);
            }
        });
        investigacionesDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                investigacionesDisponiblesActionPerformed(evt);
            }
        });
        getContentPane().add(investigacionesDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 360, -1));
        investigacionesDisponibles.getAccessibleContext().setAccessibleName("");

        jLabel1.setText("Investigaciones insertadas:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        jLabel2.setText("Seleccione uno para analizar el resumen de la investigacion seleccionada.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarArchivoActionPerformed
        JFileChooser Selector = new JFileChooser();
        int Resultado = Selector.showOpenDialog(this);
        if (Resultado == JFileChooser.APPROVE_OPTION){
            File archivoSeleccionado = Selector.getSelectedFile();
            String nombreArchivo = Selector.getName(archivoSeleccionado);
            lector = new Lector(archivoSeleccionado);
            this.lector.leer();
            if (!Table.existe(this.lector.Titulo)){
                JOptionPane.showMessageDialog(this, "Archivo: '" + nombreArchivo + "' seleccionado");
                String Autores = "";
                String Palabras = "";
                System.out.println("El titulo es: " + this.lector.Titulo);
                for (int i = 0; i < this.lector.Autores.length; i++) {
                    Autores = Autores + this.lector.Autores[i].trim();
                if (i < this.lector.Autores.length - 1) {
                    Autores = Autores + ", ";
                }}
                for (int i = 0; i < this.lector.PalabrasClav.length; i++) {
                    Palabras = Palabras + this.lector.PalabrasClav[i].trim();
                if (i < this.lector.PalabrasClav.length - 1) {
                    Palabras = Palabras + ", ";}
                }
                System.out.println("Los Autores son: " + Autores);
                System.out.println("El Resumen es: " + this.lector.Resumen);
                System.out.println("Las Palabras Claves son: " + Palabras);
                consola.setText("El titulo es: " + this.lector.Titulo + "\nLos Autores son: " + Autores + "\n" + "El Resumen es: " + this.lector.Resumen + "\nLas Palabras Claves son: " + Palabras);
                JOptionPane.showMessageDialog(this, "Archivo guardado existosamente");
                NodoArticulo Nodo = new NodoArticulo (this.lector.Titulo , this.lector.Autores, this.lector.Resumen, this.lector.PalabrasClav);
                Table.Insertar(this.lector.Titulo, Nodo);
                String cadena = this.Table.mapear();
                String[] arrCadena = cadena.split("\n");  
                consola.setText(cadena);
                DefaultComboBoxModel<String> investigaciones = new DefaultComboBoxModel<>(arrCadena);
                this.investigacionesDisponibles.setModel(investigaciones);
            }else{
                JOptionPane.showMessageDialog(this, "El Archivo: '" + nombreArchivo + "' ya habia sido seleccionado, por favor seleccione uno distinto");
            }
        }else{
            JOptionPane.showMessageDialog(this, "El usuario no insertó archivos.");
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_insertarArchivoActionPerformed

    private void investigacionesDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_investigacionesDisponiblesActionPerformed
        
        // TODO add your handling code here:
        String titulo = (String) investigacionesDisponibles.getSelectedItem();
        NodoArticulo nodo = this.Table.getNodo(this.Table.getIndiceHash(titulo));
        if (nodo != null){
            String resumen = nodo.analizarResumen();
            consola.setText(resumen);
        }
    }//GEN-LAST:event_investigacionesDisponiblesActionPerformed

    private void investigacionesDisponiblesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_investigacionesDisponiblesItemStateChanged
        // TODO add your handling code here:
        consola.setText("Si sirve");
    }//GEN-LAST:event_investigacionesDisponiblesItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Salida;
    private javax.swing.JTextArea consola;
    private javax.swing.JButton insertarArchivo;
    private javax.swing.JComboBox<String> investigacionesDisponibles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
